module.exports = {
  content: ["./*.html", "./*.js"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#006a6a",
        secondary: "#3a6665",
        tertiary: "#944a14",
        background: "#f5fbfa",
        surface: "#f5fbfa",
        "surface-tint": "#006a6a",
        "surface-dim": "#d5dbda",
        "surface-bright": "#f5fbfa",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff5f4",
        "surface-container": "#e9efee",
        "surface-container-high": "#e3e9e8",
        "surface-container-highest": "#dee4e3",
        "surface-variant": "#dee4e3",
        "on-surface": "#171d1d",
        "on-surface-variant": "#3c4949",
        "on-background": "#171d1d",
        "on-primary": "#ffffff",
        "on-primary-container": "#005151",
        "primary-container": "#41c9c9",
        "primary-fixed": "#76f6f6",
        "primary-fixed-dim": "#56d9d9",
        "on-primary-fixed": "#002020",
        "on-primary-fixed-variant": "#004f50",
        "secondary-container": "#bdebea",
        "secondary-fixed": "#bdebea",
        "secondary-fixed-dim": "#a2cfce",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#406c6b",
        "on-secondary-fixed": "#002020",
        "on-secondary-fixed-variant": "#214d4d",
        "tertiary-container": "#ff9f63",
        "tertiary-fixed": "#ffdbc9",
        "tertiary-fixed-dim": "#ffb68b",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#763500",
        "on-tertiary-fixed": "#321200",
        "on-tertiary-fixed-variant": "#753400",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        outline: "#6c7a79",
        "outline-variant": "#bbc9c8",
        "inverse-surface": "#2b3231",
        "inverse-on-surface": "#ecf2f1",
        "inverse-primary": "#56d9d9",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Newsreader", "serif"],
        body: ["Inter", "Manrope", "sans-serif"],
        label: ["Inter", "Manrope", "sans-serif"],
        display: ["Newsreader", "serif"],
      },
    },
  },
  plugins: [],
};
